(() => {
  'use strict';
  const KEY='rooznegar-final-v9', VERSION='3.0.0', MAX=8;
  const MONTHS=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
  const CATS=['اداره','شرکت برنا','شخصی','تقویت روابط عاطفی در زندگی'];
  const TB_CATS=[['borna','🏢 شرکت برنا / اداری','#635bdb'],['tech','⚡ عملیات فنی / کنتور','#e19a2b'],['study','📚 مطالعه و آموزش','#3b82f6'],['health','🏋️ سلامت و ورزش','#10a37f'],['personal','🌿 شخصی و متفرقه','#df536b']];
  const TB_TAGS=['🔥 اولویت بالا','🧠 تمرکز عمیق','📞 تماس و هماهنگی','🚗 مأموریت و تردد'];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const jp=d=>{const p=new Intl.DateTimeFormat('en-US-u-ca-persian',{year:'numeric',month:'numeric',day:'numeric'}).formatToParts(d);return {y:+p.find(x=>x.type==='year').value,m:+p.find(x=>x.type==='month').value,d:+p.find(x=>x.type==='day').value}};
  const gg=(y,m,d)=>{const a=new Date(y+621,2,19);for(let i=0;i<370;i++){const x=new Date(a);x.setDate(a.getDate()+i);const p=jp(x);if(p.y===y&&p.m===m&&p.d===d)return x}return a};
  const currentJalali=jp(new Date());let selected={...currentJalali};const dateKey=()=>`${selected.y}-${String(selected.m).padStart(2,'0')}-${String(selected.d).padStart(2,'0')}`;
  let state={days:{},habits:[],goals:[],purchases:[],ideas:[],settings:{frequentActivities:{},categories:TB_CATS.map(([id,name,color])=>({id,name,color}))}};
  try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)state={...state,...x}}catch{}
  const minutes=s=>{const [h,m]=String(s||'00:00').split(':').map(Number);return (h||0)*60+(m||0)};
  const normalizeTB=t=>{const start=t.startTime||t.start||t.time||'09:00',end=t.endTime||t.end||'10:00';return {...t,id:t.id||`tb-${Date.now()}-${Math.random()}`,date:t.date||dateKey(),title:t.title||'فعالیت بدون عنوان',categoryId:t.categoryId||t.domain||'personal',tags:Array.isArray(t.tags)?t.tags:[],startTime:start,endTime:end,durationMinutes:Math.max(0,minutes(end)-minutes(start)),notes:t.notes??t.note??'',status:t.status||'آماده انجام'}};
  Object.values(state.days).forEach(d=>{d.timeboxes=(d.timeboxes||[]).map(normalizeTB);d.gratitude=Array.isArray(d.gratitude)?d.gratitude:[]});
  const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));dispatchEvent(new CustomEvent('rooznegar:data-changed'))};
  const day=()=>{state.days[dateKey()]??={};const d=state.days[dateKey()];d.timeboxes??=[];d.gratitude??=[];return d};
  const duration=m=>`${Math.floor(m/60)?Math.floor(m/60)+' ساعت ':''}${m%60?m%60+' دقیقه':''}`.trim()||'۰ دقیقه';
  const app=document.getElementById('app');
  const nav=v=>document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));
  const render=(view='today')=>{nav(view);({today,calendar,timebox,gratitude,tasks}[view]||today)()};
  const head=(title,sub)=>`<div class="page-head"><div><h1>${title}</h1><p class="muted">${sub}</p></div></div>`;
  const sheet=(title,html,fn)=>{const o=document.createElement('div');o.className='sheet-backdrop';o.innerHTML=`<section class="bottom-sheet"><div class="sheet-handle"></div><h2>${title}</h2>${html}<div class="sheet-actions"><button class="secondary" data-x>انصراف</button><button class="primary" data-ok>ثبت</button></div></section>`;document.body.append(o);o.querySelector('[data-x]').onclick=()=>o.remove();o.querySelector('[data-ok]').onclick=()=>{if(fn(o)!==false)o.remove()};return o};
  const taskSheet=()=>sheet('افزودن کار','<label>عنوان کار<input id="st" class="input"></label><label>دسته‌بندی<select id="sc" class="input">'+CATS.map(x=>`<option>${x}</option>`).join('')+'</select></label>',o=>{const t=o.querySelector('#st').value.trim();if(!t)return false;const d=day();if(d.tasks.length>=MAX)return false;(d.tasks??=[]).push({id:Date.now(),title:t,cat:o.querySelector('#sc').value,done:false});save();today()});
  const tbSheet=(existing)=>{const t=existing?normalizeTB(existing):normalizeTB({date:dateKey()}),cats=state.settings.categories||TB_CATS.map(([id,name,color])=>({id,name,color}));const chips=Object.entries(state.settings.frequentActivities||{}).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([x])=>`<button type="button" class="frequent-chip" data-f="${esc(x)}">${esc(x)}</button>`).join('');const o=sheet(existing?'ویرایش تایم‌باکس':'افزودن تایم‌باکس',`<div class="frequent-chips">${chips}</div><label>عنوان فعالیت<input id="tt" class="input" value="${esc(t.title==='فعالیت بدون عنوان'?'':t.title)}"></label><label>حوزه کاری<select id="tc" class="input">${cats.map(c=>`<option value="${c.id}" ${c.id===t.categoryId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><details class="tags-collapse"><summary>انتخاب برچسب‌ها 🏷️</summary><div class="tag-panel">${TB_TAGS.map(x=>`<label class="tag-chip"><input type="checkbox" value="${esc(x)}" ${t.tags.includes(x)?'checked':''}><span>${x}</span></label>`).join('')}</div></details><div class="time-pair"><label>شروع<input id="ts" type="time" class="input" value="${t.startTime}"></label><label>پایان<input id="te" type="time" class="input" value="${t.endTime}"></label></div><output id="td" class="duration-output">${duration(t.durationMinutes)}</output><label>یادداشت<textarea id="tn" class="input">${esc(t.notes)}</textarea></label><label>وضعیت<select id="tv" class="input">${['آماده انجام','در حال اجرا','انجام شد ✅','لغو یا تعویق ⏭️'].map(x=>`<option ${x===t.status?'selected':''}>${x}</option>`).join('')}</select></label>`,m=>{const start=m.querySelector('#ts').value,end=m.querySelector('#te').value;const item={...t,title:m.querySelector('#tt').value.trim(),categoryId:m.querySelector('#tc').value,tags:[...m.querySelectorAll('.tag-chip input:checked')].map(x=>x.value),startTime:start,endTime:end,durationMinutes:Math.max(0,minutes(end)-minutes(start)),notes:m.querySelector('#tn').value,status:m.querySelector('#tv').value};if(!item.title)return false;day().timeboxes=day().timeboxes.map(x=>String(x.id)===String(item.id)?item:x);if(!day().timeboxes.some(x=>String(x.id)===String(item.id)))day().timeboxes.push(item);state.settings.frequentActivities[item.title]=(state.settings.frequentActivities[item.title]||0)+1;save();timebox()});['ts','te'].forEach(id=>o.querySelector('#'+id).oninput=()=>o.querySelector('#td').textContent=duration(Math.max(0,minutes(o.querySelector('#te').value)-minutes(o.querySelector('#ts').value))));o.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>o.querySelector('#tt').value=b.dataset.f)};
  function today(){const d=day();app.innerHTML=`${head('صفحه امروز','مرور و برنامه‌ریزی روزانه')}<button class="primary" id="addTask">＋ افزودن کار</button><div class="card"><h2>۳ پیروزی بزرگ امروز 🏆</h2>${[0,1,2].map(i=>`<input class="input big3-input" data-b3="${i}" value="${esc(d.big3?.[i]||'')}" placeholder="پیروزی ${i+1}">`).join('')}<button class="secondary" id="saveB3">ذخیره</button></div><div class="grid two"><div class="card">${(d.tasks||[]).map(t=>`<div class="task"><input type="checkbox" ${t.done?'checked':''}><span class="task-title">${esc(t.title)}</span></div>`).join('')||'<span class="muted">کاری ثبت نشده</span>'}</div></div>`;document.getElementById('addTask').onclick=taskSheet;document.getElementById('saveB3').onclick=()=>{d.big3=[0,1,2].map(i=>document.querySelector(`[data-b3="${i}"]`).value);save();toast('ذخیره شد')}};
  function timebox(){const d=day(),label=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'full'}).format(gg(selected.y,selected.m,selected.d));const items=d.timeboxes.map(t=>`<article class="timeline-block" data-tb="${t.id}"><b>${esc(t.startTime)} تا ${esc(t.endTime)}</b><strong>${esc(t.title)}</strong><span>${duration(t.durationMinutes)}</span><button class="primary mini" data-focus="${t.id}">آغاز فوکوس ⏱️</button></article>`).join('');app.innerHTML=`${head('تایم‌باکسینگ','خط زمانی روز انتخاب‌شده')}<div class="day-navigator"><button id="tp" class="secondary">‹</button><b>${label}</b><button id="tn" class="secondary">›</button><button id="ttoday" class="secondary">امروز</button></div><div class="card"><div class="timebox-timeline">${items||'<p class="muted">بلوک زمانی ثبت نشده است.</p>'}</div><button id="tbadd" class="primary">＋ افزودن بلوک زمانی</button></div>`;tbadd.onclick=()=>tbSheet();document.querySelectorAll('[data-tb]').forEach(b=>b.onclick=()=>tbSheet(d.timeboxes.find(x=>String(x.id)===b.dataset.tb)));document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=e=>{e.stopPropagation();focus(25)});const shift=n=>{const g=gg(selected.y,selected.m,selected.d);g.setDate(g.getDate()+n);selected=jp(g);timebox()};tp.onclick=()=>shift(-1);tn.onclick=()=>shift(1);ttoday.onclick=()=>{selected={...currentJalali};timebox()}};
  function gratitude(){const d=day(),label=new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'full'}).format(gg(selected.y,selected.m,selected.d));app.innerHTML=`${head('شکرگزاری روزانه','ثبت سه مورد برای روز انتخاب‌شده')}<div class="day-navigator"><button id="gp" class="secondary">‹</button><b>${label}</b><button id="gn" class="secondary">›</button><button id="gt" class="secondary">امروز</button></div><div class="card">${[0,1,2].map(i=>`<input class="input gratitude-input" data-g="${i}" value="${esc(d.gratitude[i]||'')}" placeholder="شکرگزاری ${i+1}">`).join('')}<button id="gs" class="primary">ذخیره</button></div>`;const shift=n=>{const g=gg(selected.y,selected.m,selected.d);g.setDate(g.getDate()+n);selected=jp(g);gratitude()};gp.onclick=()=>shift(-1);gn.onclick=()=>shift(1);gt.onclick=()=>{selected={...currentJalali};gratitude()};gs.onclick=()=>{d.gratitude=[0,1,2].map(i=>document.querySelector(`[data-g="${i}"]`).value);save();toast('ذخیره شد')}};
  function calendar(){app.innerHTML=`${head('تقویم','تقویم ماهانه')}<div class="card">تقویم ماه ${MONTHS[selected.m-1]} ${selected.y}</div>`}
  function tasks(){app.innerHTML=`${head('همه کارها','فهرست کارها')}<div class="card">${Object.values(state.days).flatMap(d=>d.tasks||[]).map(t=>`<div class="task">${esc(t.title)}</div>`).join('')||'—'}</div>`}
  const toast=s=>{const e=document.getElementById('toast');if(e){e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}};
  const focus=min=>{const o=document.createElement('div');o.className='focus-overlay';let left=min*60;o.innerHTML=`<section class="focus-card"><div class="focus-ring"><span id="fv">${min}:00</span></div><button class="primary" id="fs">پایان فوکوس</button></section>`;document.body.append(o);const id=setInterval(()=>{left--;o.querySelector('#fv').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(id);o.remove()}},1000);o.querySelector('#fs').onclick=()=>{clearInterval(id);o.remove()}};
  window.rooznegar={getData:()=>state,replaceData:x=>{state={...state,...x};save();render()},render};
  document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>render(n.dataset.view));document.getElementById('todayBtn').onclick=()=>render('today');document.getElementById('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state)],{type:'application/json'}));a.download='rooznegar.json';a.click()};document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'))};
  render('today');
})();
